fix: add missing encoding for media links
FlowingCode/ShareEasy pull request #11
Opened 2024-05-13 11:50 UTC by paodb

Close #10

2024-05-13 12:17 UTC, javier-godoy commented
I think this may be a breaking change, since instead of `setShareLink("https%3A%2F%2Fgoogle.com%2Fhello%2F%3Fparam1%3DValue%2520Space%26lang%3Den'")` (already encoded), now the URL is encoded by the component, and the user has to specify `setShareLink(""https://google.com/hello/?param1=Value%20Space&lang=en")`, which is a nice improvement, but breaks the current behavior.

2024-05-14 13:58 UTC, javier-godoy requested changes
Update pom version

2024-05-14 14:24 UTC, paodb commented
> Update pom version

Done.

2024-05-14 14:42 UTC, javier-godoy approved these changes

2024-05-14 14:42 UTC, merged